# Autonomous Systems A Lab - Project Organization Notebook

This notebook is a structured project companion for the **Autonomous Systems A Lab**.

Use it to:
- organize the team,
- track responsibilities,
- document progress,
- prepare milestones,
- collect evidence of practical work,
- prepare final presentation and paper.

Use the checkboxes `- [ ]` / `- [x]` to track what is done.

> Recommendation: Commit this notebook regularly to your team GitHub repository.

## Project context

The lab is motivated by **truck platooning** and ADAS.

The project combines:
1. SVM-based line following,
2. scenario and requirements modelling,
3. communication/protocol specification,
4. timed automata and UPPAAL modelling,
5. control behaviour,
6. simulation and integration,
7. final presentation and documentation.

# 0. Team and Repository Setup

## Objective
Prepare the technical and organisational foundation.

## Checklist
- [x] Team members are defined.
- [x] GitHub repository is created.
- [x] Professors are invited: `shenkler`, `mahirsch`.
- [x] Research assistants are invited: `AAT24`, `Krypto-Klaus`, `NordBaha`, `DomeDre`.
- [x] Repository has a clear folder structure.
- [x] All members can push and pull.
- [x] This notebook is committed.
- [x] Responsibilities are documented.

## Deadline
- May 15 during the lab session, ideally earlier.

## Suggested repository structure
```text
project-root/
├── notebooks/
├── src/
├── models/
├── data/
├── results/
└── documentation/
```

In [1]:
import pandas as pd

team_name = "Group 4"
repository_url = "https://github.com/dccelectronicsgermany/Autonomous_Systems_A_Lab_Group_4.git"

# The ML lab pipeline was divided into four stages, one per member.
# In the CPS lab, each member owned one platooning scenario end to end.
team_members = [
    {"name": "Daniel Chidi Chimezie", "matriculation": "1230515", "role": "Project Manager",
     "ml_lab_stage": "Science Truck data collection, dataset preparation",
     "cps_lab_scenario": "Communication failure; coordination of shared channels"},
    {"name": "Riwaj Ghimire", "matriculation": "1232171", "role": "DevOps Manager",
     "ml_lab_stage": "Feature pipeline and SVR training",
     "cps_lab_scenario": "Emergency braking scenario and UPPAAL model"},
    {"name": "Stephen Uzochi Obuh", "matriculation": "2210044", "role": "System Integration Lead",
     "ml_lab_stage": "Hyperparameter tuning and ROS 2 deployment",
     "cps_lab_scenario": "Platoon splitting; integration of the combined model"},
    {"name": "Bertrand Mungu Cho", "matriculation": "2220052", "role": "Verification and Testing Lead",
     "ml_lab_stage": "Model testing and evaluation",
     "cps_lab_scenario": "Platoon formation; deadlock-freedom verification"},
]
pd.DataFrame(team_members)

,name,matriculation,role,ml_lab_stage,cps_lab_scenario
0,Daniel Chidi Chimezie,1230515,Project Manager,"Science Truck data collection, dataset prepara...",Communication failure; coordination of shared ...
1,Riwaj Ghimire,1232171,DevOps Manager,Feature pipeline and SVR training,Emergency braking scenario and UPPAAL model
2,Stephen Uzochi Obuh,2210044,System Integration Lead,Hyperparameter tuning and ROS 2 deployment,Platoon splitting; integration of the combined...
3,Bertrand Mungu Cho,2220052,Verification and Testing Lead,Model testing and evaluation,Platoon formation; deadlock-freedom verification

# 1. Responsibility Matrix

## Objective
Divide the project into clear tasks and assign responsibilities.

The module consisted of two labs: Task 1 belongs to the **Machine Learning lab** (May, weekly deadlines, competition on May 22) and Tasks 2 to 6 belong to the **Cyber-Physical Systems lab** (June, milestone-based). Both are documented together in the final report, since the CPS lab builds directly on the single-vehicle capability from the ML lab.

Every member contributed to both labs. In the ML lab the pipeline was divided into four stages: Daniel handled Science Truck data collection and dataset preparation, Riwaj built the feature pipeline and trained the SVR, Stephen ran the hyperparameter tuning and the ROS 2 deployment, and Bertrand tested and evaluated the trained model. In the CPS lab, each member owned one platooning scenario end to end.

## Checklist
- [x] Overall task list created.
- [x] Each task has a short summary.
- [x] Each task has one responsible member.
- [x] Each task has a deadline.
- [x] Progress status is documented.
- [x] Finished tasks include finishing date.
- [x] Matrix is updated continuously.

| # | Task | Lab | Short Summary | Responsible | Todo / Deadline | Done / Finishing Date |
|---|------|-----|---------------|-------------|-----------------|-----------------------|
| 1 | SVM line following | ML lab | 6-feature extraction pipeline + tuned RBF SVR + PD controller (`my_line_follower.py`) | Daniel: Science Truck data collection, dataset preparation; Riwaj: feature pipeline + SVR training; Stephen: tuning + ROS 2 deployment; Bertrand: model testing + evaluation | May 21 (upload), May 22 (competition) | Done / May 21 - competition May 22, placed among top teams |
| 2 | Scenario modelling | CPS lab | 4 scenarios described and modelled in SysML/UML (1 per member) | Daniel: Communication Failure, Riwaj: Emergency Braking, Bertrand: Platoon Formation, Stephen: Platoon Splitting | June 4 (Milestone 1) | Done / June 4 |
| 3 | Communication protocol | CPS lab | Data/signals/events + protocol per scenario, timed automata in UPPAAL | Each member for their own scenario | June 11 (Milestone 2) | Done / June 11 |
| 4 | Control behaviour | CPS lab | Distance keeping, emergency braking, communication-failure fallback (UPPAAL) | Whole team | June 18 (Milestone 3) | Done / June 18 |
| 5 | Simulation integration | CPS lab | Integrated UPPAAL model (lead + follower + distance controller + communication monitor), deadlock-freedom verification | Integration lead: Stephen; verification: Bertrand; whole team contributed | June 25 (Milestone 5) | Done / July 3 (final `A[] not deadlock` verification) |
| 6 | Final presentation | Both | Slides + live UPPAAL demonstration incl. verification results | Whole team (each member presents own part) | Slides: July 9, 1:00 PM; session: July 10, 9:00 AM | In progress |
| 7 | Final paper | Both | LNI-template report (max 10 pages) + ZIP with PDF and all UPPAAL files | Whole team | July 10, 11:59 PM (Moodle) | In progress |

# 2. Task 1 - SVM-Based Line Following

## Objective
Implement an **SVM-based line-following approach** using scikit-learn.

## Required elements
- version for lane following,
- own test data,
- OpenCV usage,
- parameter and kernel optimization,
- CARLA competition environment,
- CARLA input to refine line following,
- Science Truck data to refine final SVM.

## Checklist - Preparation
- [x] Lab 05 to 07 completed.
- [x] Python environment works.
- [x] scikit-learn workflow understood.
- [x] OpenCV basics tested.

## Checklist - Dataset
- [x] Synthetic test data generated.
- [x] Feature representation defined - 6 features: `[off_bot, off_mid, off_top, has_bot, has_mid, has_top]` from a perspective-correct trapezoid ROI.
- [x] Labels/classes defined - continuous steering target in [-1, +1] via geometric labeling formula (regression instead of classification).
- [x] Dataset documented - 17,046 camera frames, see `01_extract_dataset.ipynb`.
- [x] Train/test split applied - temporal block split (last 20% held out) to avoid adjacent-frame leakage.
- [x] CARLA data considered.
- [x] Science Truck data integrated - final dataset extracted from Science Truck camera frames.

## Checklist - Model
- [x] Linear SVM trained (lab exercises).
- [x] RBF SVM trained - final model is an RBF **SVR** (regression on steering offset).
- [x] Parameter `C` investigated - grid search, best `C=5`.
- [x] Parameter `gamma` investigated - best `gamma=0.1` (plus `epsilon=0.01`).
- [x] Feature scaling applied - `StandardScaler` fit on train only.
- [x] Pipeline used to avoid data leakage - `Pipeline(StandardScaler -> SVR)`, TimeSeriesSplit CV.
- [x] Best model selected - tuned SVR, deployed as `Trapezoid_V2_sharp_turns.pkl`.

## Checklist - Evaluation
- [x] Accuracy reported - Test MAE 0.0075, Test R² 0.9909 (regression metrics; 62% MAE improvement over baseline).
- [x] Confusion matrix reported - for the classification labs; the final model is a regressor, evaluated with MAE/R² and permutation feature importance instead.
- [x] Critical scenarios identified - sharp turns (fixed via 3× curve sample weighting), missing bands, noise blobs (row-span rejection).
- [x] Limitations discussed - gains beyond throttle 0.40 untested; single green-line track assumption.
- [x] Trained model saved.
- [x] Notebook uploaded to Moodle per person.
- [x] Final model committed to GitHub.

## Deadlines
- May 15: finalize and present lab exercises 01-07; upload all `.ipynb` files to Moodle per person. done
- May 18: gather detailed data in Science Truck and refine SVM. done
- May 19: upload trained SVM based on gathered data until EOB. done
- May 20: test SVM and gather additional critical scenarios. done
- May 21: final upload to GitHub until EOB. done
- May 22: competition in Science Truck starting 09:00. done - placed among the top teams.

In [2]:
task_1_status = {
    "synthetic_data_created": True,
    "opencv_used": True,                 # HSV masking, morphology, trapezoid ROI, contour/moment analysis
    "linear_svm_trained": True,          # lab exercises
    "rbf_svm_trained": True,             # final RBF SVR: C=5, gamma=0.1, epsilon=0.01
    "parameters_optimized": True,        # grid search with TimeSeriesSplit CV (36 candidates, 5 temporal folds)
    "carla_data_used": True,
    "science_truck_data_used": True,     # 17,046 frames
    "final_model_uploaded": True,        # Trapezoid_V2_sharp_turns.pkl - Test MAE 0.0075, R² 0.9909
}
pd.DataFrame(list(task_1_status.items()), columns=["check", "done"])

                     check  done
0   synthetic_data_created  True
1              opencv_used  True
2       linear_svm_trained  True
3          rbf_svm_trained  True
4     parameters_optimized  True
5          carla_data_used  True
6  science_truck_data_used  True
7     final_model_uploaded  True

# 3. Task 2 - Scenario Identification and Requirements

## Objective
Identify relevant scenarios, requirements, and timing behaviour.

Each group member is responsible for at least one scenario.

## Checklist
- [x] Each group member selected at least one scenario.
- [x] Scenario descriptions written (README per scenario in `truck_platooning/scenarios/`).
- [x] Functional requirements identified.
- [x] Non-functional requirements identified (communication reliability, latency, robustness).
- [x] Timing requirements identified (per-scenario timing constraint tables).
- [x] Safety requirements identified (e.g. SR-EB-01 … SR-EB-06 for emergency braking).
- [x] Assumptions documented (preconditions, trigger events, alternative/exception flows).
- [x] Scenarios modelled using SysML/UML (PlantUML: sequence, state machine, activity, requirement, use case diagrams).
- [x] Models committed to GitHub.

## Milestone 1
- Due: June 4, EOB. done Completed.

In [3]:
scenarios = [
    {
        "scenario_name": "Communication Failure (SC-COM-01)",
        "responsible_member": "Daniel Chidi Chimezie",
        "short_description": "One or more trucks lose V2V communication with the platoon. "
                             "A watchdog detects missing heartbeat messages, the affected trucks "
                             "enter a fail-safe mode with increased gaps, and reconnection is "
                             "attempted periodically until communication is restored.",
        "functional_requirements": [
            "Monitor V2V communication channels continuously (heartbeat/status messages)",
            "Detect communication failure when the timeout threshold is exceeded",
            "Enter fail-safe mode upon confirmed failure",
            "Attempt automatic reconnection at regular intervals",
            "Resume normal platoon operation once communication is restored",
        ],
        "timing_requirements": [
            "Failure detection within the configured timeout period",
            "Recovery attempt every RECOVERY_TIME = 10 s (UPPAAL model)",
        ],
        "safety_requirements": [
            "Fail-safe mode entered whenever communication is lost",
            "Safe inter-vehicle distance must hold before entering safe mode (safeDistance guard)",
            "Emergency braking remains available in every communication state",
            "Alarm/notification generated on failure detection",
        ],
        "model_file": "truck_platooning/scenarios/01_communication_failure/uppaal_design_communication_failure/uppal_communication.xml",
    },
    {
        "scenario_name": "Emergency Braking (SC-EB-02)",
        "responsible_member": "Riwaj Ghimire",
        "short_description": "The lead truck detects an obstacle, applies maximum braking and "
                             "broadcasts EMERGENCY_BRAKE_SIGNAL via V2V. All followers brake "
                             "immediately without human reaction delay; sensor-based collision "
                             "avoidance is the fallback if V2V is unavailable.",
        "functional_requirements": [
            "Detect obstacles via onboard sensors and trigger emergency braking",
            "Broadcast emergency brake signal to all platoon members via V2V",
            "Apply emergency braking on all followers upon signal reception",
            "Acknowledge signal receipt and report braking status to Platoon Manager",
            "Fall back to sensor-based collision avoidance if V2V is unavailable",
        ],
        "timing_requirements": [
            "Hazard detection to brake activation <= 50 ms",
            "Emergency signal broadcast latency <= 100 ms",
            "Follower brake activation after signal <= 150 ms",
            "Sensor-based fallback activation <= 200 ms",
            "Full platoon stop from signal <= 5 s",
        ],
        "safety_requirements": [
            "SR-EB-01 … SR-EB-06: braking within deadlines, no jackknifing deceleration,",
            "single-truck braking failure must not cascade into chain-reaction collision",
        ],
        "model_file": "truck_platooning/scenarios/02_emergency_braking/upaal_design_emergency-braking/emergency_braking.xml",
    },
    {
        "scenario_name": "Platoon Formation",
        "responsible_member": "Bertrand Mungu Cho",
        "short_description": "A lead truck broadcasts a platoon advertisement; follower trucks "
                             "send join requests, the Platoon Manager evaluates and approves them, "
                             "assigns slots and gaps, and a coordinated formation maneuver "
                             "transitions the vehicles into normal platoon operation.",
        "functional_requirements": [
            "Detect available platoons (advertisement broadcast)",
            "Process join requests (ID, capabilities, position)",
            "Assign platoon positions, roles and target gaps",
            "Coordinate the formation maneuver and monitor vehicle status",
            "Confirm successful platoon formation",
        ],
        "timing_requirements": [
            "Advertisement reception <= 200 ms",
            "Join request forwarding <= 100 ms",
            "Join approval decision <= 500 ms",
            "Formation completion <= 1 s",
        ],
        "safety_requirements": [
            "Maintain safe inter-vehicle gaps during the maneuver",
            "Validate vehicle capabilities before approving membership",
            "Detect communication failures during formation",
        ],
        "model_file": "truck_platooning/scenarios/03_platoon_formation/uppaal_design_platoon_formation/truck_platoon_formation.xml",
    },
    {
        "scenario_name": "Platoon Splitting",
        "responsible_member": "Stephen Uzochi Obuh",
        "short_description": "At a route divergence the platoon (1 lead + 3 followers) splits into "
                             "two independent sub-platoons: gap creation, physical separation, "
                             "leader promotion for the second group, V2V topology reconfiguration "
                             "and stabilization of both sub-platoons.",
        "functional_requirements": [
            "Detect an upcoming route divergence from navigation data",
            "Negotiate the split (new leader, split point, synchronization)",
            "Create safe separation gaps between future sub-platoons",
            "Reconfigure V2V topology and reassign leadership roles",
            "Stabilize both sub-platoons into steady-state operation",
        ],
        "timing_requirements": [
            "Split negotiation: 100 ms - several seconds",
            "Gap creation: 2 - 10 s",
            "Physical separation: 1 - 5 s",
            "Topology reconfiguration: < 1 s to a few seconds",
            "Stabilization: 5 - 20 s",
        ],
        "safety_requirements": [
            "Safe inter-vehicle gaps throughout the entire maneuver",
            "Reliable V2V communication within each new sub-platoon",
            "Minimal disruption to surrounding traffic",
        ],
        "model_file": "truck_platooning/scenarios/04_platoon_splitting/uppaal_design_platoon_splitting/PlatoonSplit.xml",
    },
]

# Summary table (full requirement lists remain in the `scenarios` variable above)
pd.DataFrame([
    {
        "scenario_name": s["scenario_name"],
        "responsible_member": s["responsible_member"],
        "short_description": s["short_description"],
        "functional_requirements": len(s["functional_requirements"]),
        "timing_requirements": len(s["timing_requirements"]),
        "safety_requirements": len(s["safety_requirements"]),
        "model_file": s["model_file"],
    }
    for s in scenarios
])

,scenario_name,responsible_member,short_description,functional_requirements,timing_requirements,safety_requirements,model_file
0,Communication Failure (SC-COM-01),Daniel Chidi Chimezie,One or more trucks lose V2V communication with...,5,2,4,truck_platooning/scenarios/01_communication_fa...
1,Emergency Braking (SC-EB-02),Riwaj Ghimire,"The lead truck detects an obstacle, applies ma...",5,5,2,truck_platooning/scenarios/02_emergency_brakin...
2,Platoon Formation,Bertrand Mungu Cho,A lead truck broadcasts a platoon advertisemen...,5,4,3,truck_platooning/scenarios/03_platoon_formatio...
3,Platoon Splitting,Stephen Uzochi Obuh,At a route divergence the platoon (1 lead + 3 ...,5,5,3,truck_platooning/scenarios/04_platoon_splittin...

# 4. Task 3 - Communication Data, Signals, Events, and Protocols

## Objective
Identify data/signals/events required for interaction and communication between trucks.

Specify an appropriate protocol for each scenario. Use Timed Automata and UPPAAL.

## Checklist
- [x] Required data between trucks identified (speed, position, lane, gap, truck status, capabilities).
- [x] Required signals listed (see `communication_items` below - UPPAAL channels).
- [x] Required events listed (obstacle detected, gap too small, comm failure, comm restored, …).
- [x] Sender and receiver defined for every channel.
- [x] Timing assumptions defined (BRAKE_TIME = 100, GAP_TIME = 500, RECOVERY_TIME = 10000, STATUS_TIME = 100).
- [x] Protocol defined for each scenario (data/signal/event PDFs per scenario folder).
- [x] Communication failure considered (dedicated scenario + CommunicationMonitor automaton).
- [x] Timed automata created.
- [x] UPPAAL model created (one per scenario + integrated model).
- [x] Models committed to GitHub.

## Milestone 2
- Due: June 11, EOB. done Completed.

In [4]:
# Channels of the integrated UPPAAL model
# (01_Final_Version_Truck_Platooning_Control_Behaviour.xml)
communication_items = [
    {
        "name": "statusUpdate",
        "type": "event",
        "sender": "LeadTruckControl",
        "receiver": "FollowerTruckControl",
        "meaning": "Periodic status broadcast (speed/position) from the lead truck",
        "timing_constraint": "tStatus <= STATUS_TIME (100 ms)",
        "related_scenario": "Normal platoon operation",
    },
    {
        "name": "emergencyBrake",
        "type": "event (broadcast channel)",
        "sender": "LeadTruckControl",
        "receiver": "all FollowerTruckControl instances",
        "meaning": "Emergency brake signal after obstacle detection - receivable from every follower state",
        "timing_constraint": "tBrake <= BRAKE_TIME (100 ms) from obstacle detection",
        "related_scenario": "Emergency Braking (SC-EB-02)",
    },
    {
        "name": "obstacleCleared",
        "type": "event (broadcast channel)",
        "sender": "LeadTruckControl",
        "receiver": "all FollowerTruckControl instances",
        "meaning": "Obstacle removed - platoon returns from EmergencyStop to normal following",
        "timing_constraint": "none (operator/lead decision)",
        "related_scenario": "Emergency Braking (SC-EB-02)",
    },
    {
        "name": "gapTooSmall",
        "type": "signal",
        "sender": "DistanceController",
        "receiver": "FollowerTruckControl",
        "meaning": "Inter-vehicle gap dropped below the safe threshold (safeDistance = false)",
        "timing_constraint": "correction must start within tGap <= GAP_TIME (500 ms)",
        "related_scenario": "Distance keeping / control behaviour",
    },
    {
        "name": "safeGapRestored",
        "type": "signal",
        "sender": "DistanceController",
        "receiver": "FollowerTruckControl",
        "meaning": "Gap corrected back to safe distance (safeDistance = true)",
        "timing_constraint": "tGap <= GAP_TIME (500 ms)",
        "related_scenario": "Distance keeping / control behaviour",
    },
    {
        "name": "commFailure",
        "type": "event",
        "sender": "CommunicationMonitor",
        "receiver": "FollowerTruckControl",
        "meaning": "V2V communication failure detected (missing heartbeat/timeout)",
        "timing_constraint": "resets tRecovery",
        "related_scenario": "Communication Failure (SC-COM-01)",
    },
    {
        "name": "enterSafeMode",
        "type": "event",
        "sender": "CommunicationMonitor",
        "receiver": "FollowerTruckControl",
        "meaning": "Activate fail-safe mode (guarded by safeDistance == true)",
        "timing_constraint": "SafeMode invariant: tRecovery <= TOTAL_RECOVERY_TIME (N × 10 s)",
        "related_scenario": "Communication Failure (SC-COM-01)",
    },
    {
        "name": "recoveryAttempt",
        "type": "event",
        "sender": "CommunicationMonitor",
        "receiver": "FollowerTruckControl",
        "meaning": "Periodic attempt to re-establish communication",
        "timing_constraint": "tRecovery >= RECOVERY_TIME (10 s) between attempts",
        "related_scenario": "Communication Failure (SC-COM-01)",
    },
    {
        "name": "commRestored",
        "type": "event",
        "sender": "CommunicationMonitor",
        "receiver": "FollowerTruckControl",
        "meaning": "Communication link re-established - resume normal following",
        "timing_constraint": "none",
        "related_scenario": "Communication Failure (SC-COM-01)",
    },
]
pd.DataFrame(communication_items)

,name,type,sender,receiver,meaning,timing_constraint,related_scenario
0,statusUpdate,event,LeadTruckControl,FollowerTruckControl,Periodic status broadcast (speed/position) fro...,tStatus <= STATUS_TIME (100 ms),Normal platoon operation
1,emergencyBrake,event (broadcast channel),LeadTruckControl,all FollowerTruckControl instances,Emergency brake signal after obstacle detectio...,tBrake <= BRAKE_TIME (100 ms) from obstacle de...,Emergency Braking (SC-EB-02)
2,obstacleCleared,event (broadcast channel),LeadTruckControl,all FollowerTruckControl instances,Obstacle removed - platoon returns from Emerge...,none (operator/lead decision),Emergency Braking (SC-EB-02)
3,gapTooSmall,signal,DistanceController,FollowerTruckControl,Inter-vehicle gap dropped below the safe thres...,correction must start within tGap <= GAP_TIME ...,Distance keeping / control behaviour
4,safeGapRestored,signal,DistanceController,FollowerTruckControl,Gap corrected back to safe distance (safeDista...,tGap <= GAP_TIME (500 ms),Distance keeping / control behaviour
5,commFailure,event,CommunicationMonitor,FollowerTruckControl,V2V communication failure detected (missing he...,resets tRecovery,Communication Failure (SC-COM-01)
6,enterSafeMode,event,CommunicationMonitor,FollowerTruckControl,Activate fail-safe mode (guarded by safeDistan...,SafeMode invariant: tRecovery <= TOTAL_RECOVER...,Communication Failure (SC-COM-01)
7,recoveryAttempt,event,CommunicationMonitor,FollowerTruckControl,Periodic attempt to re-establish communication,tRecovery >= RECOVERY_TIME (10 s) between atte...,Communication Failure (SC-COM-01)
8,commRestored,event,CommunicationMonitor,FollowerTruckControl,Communication link re-established - resume nor...,none,Communication Failure (SC-COM-01)

# 5. Task 4 - Control Behaviour

## Objective
Identify relevant control behaviour for the trucks.

Guiding questions:
- How can distance to the preceding truck be guaranteed? -> DistanceController automaton: `gapTooSmall` -> braking -> `safeGapRestored` within GAP_TIME (500 ms).
- What happens during communication failure? -> CommunicationMonitor: fail-safe mode (only if `safeDistance` holds), periodic recovery every 10 s.
- Is the system robust and stable? -> Emergency braking is a broadcast channel receivable from **every** follower state; verified deadlock-free.
- Which fallback behaviour is required? -> Safe mode with increased gaps; sensor-based collision avoidance when V2V is down; hold-last-steer / neutral fallback in the line follower.

Use Timed Automata and UPPAAL.

## Checklist
- [x] Relevant control behaviours identified (see `control_behaviours` below).
- [x] Distance-keeping specified (DistanceController + MaintainGap/GapTooSmall/Braking states).
- [x] Lane-following linked to SVM results (SVR steering offset -> PD controller in `my_line_follower.py`).
- [x] Failure cases identified (communication loss, gap violation, obstacle, line lost).
- [x] Communication failure behaviour specified (safe mode + recovery loop).
- [x] Robustness assumptions documented (emergencyBrake receivable in all states; blob rejection and hold-last-steer in line follower).
- [x] Stability considerations documented (PD gain table per throttle band; safeDistance guard before safe mode).
- [x] UPPAAL model created or extended (integrated control behaviour model).
- [x] Control model committed to GitHub.

## Milestone 3
- Due: June 18, EOB. done Completed.

In [5]:
control_behaviours = [
    {
        "behaviour_name": "Distance keeping (gap control)",
        "related_scenario": "Normal platoon operation / all scenarios",
        "input_signals": ["gapTooSmall", "safeGapRestored", "statusUpdate"],
        "control_decision": "On gapTooSmall the follower brakes until the safe gap is restored "
                            "(MaintainGap -> GapTooSmall -> Braking -> SafeGapRestored)",
        "safety_condition": "Gap correction within tGap <= GAP_TIME (500 ms); safeDistance flag tracks state",
        "failure_handling": "Emergency braking overrides gap control from every state",
        "model_file": "truck_platooning/scenarios/00_Truck_Platooning_Control_Behaviour/01_Final_Version_Truck_Platooning_Control_Behaviour.xml",
    },
    {
        "behaviour_name": "Emergency braking",
        "related_scenario": "Emergency Braking (SC-EB-02)",
        "input_signals": ["emergencyBrake (broadcast)", "obstacleCleared (broadcast)"],
        "control_decision": "Lead truck detects obstacle, broadcasts emergencyBrake within "
                            "BRAKE_TIME (100 ms); every follower transitions to EmergencyStop "
                            "regardless of its current state",
        "safety_condition": "tBrake <= BRAKE_TIME; emergencyBrake receivable from ALL follower states",
        "failure_handling": "Sensor-based collision avoidance as fallback when V2V is unavailable",
        "model_file": "truck_platooning/scenarios/00_Truck_Platooning_Control_Behaviour/01_Final_Version_Truck_Platooning_Control_Behaviour.xml",
    },
    {
        "behaviour_name": "Communication-failure fallback (safe mode)",
        "related_scenario": "Communication Failure (SC-COM-01)",
        "input_signals": ["commFailure", "enterSafeMode", "recoveryAttempt", "commRestored"],
        "control_decision": "On commFailure the follower enters SafeMode (only if safeDistance holds) "
                            "and periodically attempts recovery until commRestored",
        "safety_condition": "SafeMode invariant tRecovery <= TOTAL_RECOVERY_TIME; recovery attempts "
                            "every RECOVERY_TIME (10 s)",
        "failure_handling": "Emergency braking still receivable in SafeMode/Recovery/Restored states",
        "model_file": "truck_platooning/scenarios/00_Truck_Platooning_Control_Behaviour/01_Final_Version_Truck_Platooning_Control_Behaviour.xml",
    },
    {
        "behaviour_name": "Lane following (SVM/SVR + PD control)",
        "related_scenario": "Task 1 - line following (links ML task to control behaviour)",
        "input_signals": ["camera frames (720×1280 BGR, ~30 fps)"],
        "control_decision": "6-feature extraction (trapezoid ROI, 3 line bands) -> SVR predicts "
                            "steering offset -> PD controller (throttle-dependent Kp/Kd gain table) "
                            "outputs steering in [-1, +1]",
        "safety_condition": "Blob rejection (row-span check) filters noise; steering clipped to [-1, 1]",
        "failure_handling": "Hold last steer for up to 10 lost frames, then return None -> "
                            "framework neutral-steering fallback + 'Line lost!' alert",
        "model_file": "Final ML files/final_my_line_following_solution/my_line_follower.py",
    },
]

control_behaviours_table = pd.DataFrame(control_behaviours).assign(
    input_signals=lambda d: d["input_signals"].apply(", ".join)
)
control_behaviours_table

,behaviour_name,related_scenario,input_signals,control_decision,safety_condition,failure_handling,model_file
0,Distance keeping (gap control),Normal platoon operation / all scenarios,"gapTooSmall, safeGapRestored, statusUpdate",On gapTooSmall the follower brakes until the s...,Gap correction within tGap <= GAP_TIME (500 ms...,Emergency braking overrides gap control from e...,truck_platooning/scenarios/00_Truck_Platooning...
1,Emergency braking,Emergency Braking (SC-EB-02),"emergencyBrake (broadcast), obstacleCleared (b...","Lead truck detects obstacle, broadcasts emerge...",tBrake <= BRAKE_TIME; emergencyBrake receivabl...,Sensor-based collision avoidance as fallback w...,truck_platooning/scenarios/00_Truck_Platooning...
2,Communication-failure fallback (safe mode),Communication Failure (SC-COM-01),"commFailure, enterSafeMode, recoveryAttempt, c...",On commFailure the follower enters SafeMode (o...,SafeMode invariant tRecovery <= TOTAL_RECOVERY...,Emergency braking still receivable in SafeMode...,truck_platooning/scenarios/00_Truck_Platooning...
3,Lane following (SVM/SVR + PD control),Task 1 - line following (links ML task to cont...,"camera frames (720×1280 BGR, ~30 fps)","6-feature extraction (trapezoid ROI, 3 line ba...",Blob rejection (row-span check) filters noise;...,"Hold last steer for up to 10 lost frames, then...",Final ML files/final_my_line_following_solutio...

# 6. Task 5 - Integration and Simulation

## Objective
Implement a simulation integrating the specific tasks.

The simulation deliverable is the **integrated UPPAAL model**
(`00_Truck_Platooning_Control_Behaviour/01_Final_Version_Truck_Platooning_Control_Behaviour.xml`),
which combines the scenario logic, communication protocol, control behaviour and timing
assumptions in four parallel timed automata. The SVM line follower covers the lane-keeping
part on the real vehicle (Science Truck competition).

## Checklist
- [x] Simulation goal defined - verify safe, deadlock-free coordination of a 4-truck platoon.
- [x] Simulation architecture defined - 4 parallel automata: LeadTruckControl, FollowerTruckControl, DistanceController, CommunicationMonitor.
- [x] Inputs and outputs specified - channels + timing constants (see `communication_items`).
- [x] SVM component integrated - lane keeping on the vehicle via `my_line_follower.py`; represented as the follower's normal-following behaviour in the model.
- [x] Communication behaviour integrated - statusUpdate protocol + CommunicationMonitor failure/recovery loop.
- [x] Control behaviour integrated - distance keeping, emergency braking, safe-mode fallback.
- [x] At least one scenario simulated - symbolic simulator runs (see `symbolic_simulator.png` screenshots).
- [x] Critical scenario simulated - emergency braking during communication failure (broadcast reaches followers in all states).
- [x] Results documented - verification query `A[] not deadlock` **passed** (UPPAAL, 2026-07-03), proof of deadlock freedom stored in the model file.
- [x] Simulation committed to GitHub.

## Milestone 5
- Due: June 25, EOB. done Completed (final verification July 3).

In [6]:
simulation_plan = {
    "simulation_goal": "Verify safe, deadlock-free coordination of a 4-truck platoon "
                       "(1 lead + 3 followers) covering status updates, distance keeping, "
                       "emergency braking and communication-failure recovery",
    "integrated_components": [
        "LeadTruckControl (status broadcast, obstacle detection, emergency braking)",
        "FollowerTruckControl (normal following, gap handling, emergency stop, safe mode)",
        "DistanceController (gap monitoring and correction)",
        "CommunicationMonitor (failure detection, safe mode, recovery loop)",
        "SVM line follower (lane keeping on the real vehicle, my_line_follower.py)",
    ],
    "scenarios_to_simulate": [
        "Normal platoon operation with periodic status updates",
        "Gap-too-small detection and correction (GAP_TIME = 500 ms)",
        "Emergency braking broadcast from every follower state (critical scenario)",
        "Communication failure -> safe mode -> periodic recovery -> restoration",
    ],
    "expected_outputs": [
        "Symbolic simulator traces for each scenario",
        "Verification result: A[] not deadlock - PASSED (UPPAAL, 2026-07-03)",
    ],
    "result_files": [
        "truck_platooning/scenarios/00_Truck_Platooning_Control_Behaviour/01_Final_Version_Truck_Platooning_Control_Behaviour.xml",
        "truck_platooning/scenarios/00_Truck_Platooning_Control_Behaviour/symbolic_simulator.png",
    ],
}

pd.DataFrame([
    {"field": k, "value": "; ".join(v) if isinstance(v, list) else v}
    for k, v in simulation_plan.items()
])

                   field                                              value
0        simulation_goal  Verify safe, deadlock-free coordination of a 4...
1  integrated_components  LeadTruckControl (status broadcast, obstacle d...
2  scenarios_to_simulate  Normal platoon operation with periodic status ...
3       expected_outputs  Symbolic simulator traces for each scenario; V...
4           result_files  truck_platooning/scenarios/00_Truck_Platooning...

# 7. Final Presentation

## Objective
Present the complete project including a live demonstration.

**Status (July 8):** slides are being prepared separately - submission deadline **Thursday, July 9, 1:00 PM (Moodle)**; presentation session **Friday, July 10, 9:00 AM** (attendance mandatory, max 20 minutes for a team of 4, ~5 minutes per member).

Required content per the guideline:
- Machine Learning tasks - overview and results.
- Truck platooning - requirements and scenarios overview.
- **Live demonstration of the overall UPPAAL simulation.**
- **Verification results incl. proof of deadlock freedom** (`A[] not deadlock` - already verified, stored in the final model file).

## Checklist
- [x] Presentation structure defined (follows the guideline content above).
- [ ] Each group member has a speaking part.
- [x] Live demonstration prepared - integrated UPPAAL model with symbolic simulator and saved passing deadlock-freedom query.
- [ ] Technical backup prepared (screenshots of symbolic simulator + verification exist as fallback).
- [ ] Results visualized.
- [ ] Main limitations discussed.
- [ ] Each group member can answer questions.
- [ ] Final slides committed to GitHub.

## Requirements
- Slides deadline: July 9, 1:00 PM via Moodle.
- Session: July 10, 9:00 AM, live demonstration included.
- Every group member must be able to answer questions.

# 8. Final Paper / Documentation

## Objective
Document the complete project in scientific form.

**Status (July 8):** LNI template prepared (title, authors, section skeleton, declaration of originality); content writing in progress. Deadline per the final guideline: **Friday, July 10, 11:59 PM via Moodle**, as a **ZIP archive** containing the report PDF **and all UPPAAL model files**. Maximum length: **10 pages**, CPS Seminar (LNI) template.

## Required content
- motivation,
- scenario descriptions,
- requirements,
- SysML/UML models,
- Timed Automata / UPPAAL models,
- SVM approach,
- datasets and evaluation,
- simulation,
- results,
- limitations,
- references.

## Checklist
- [x] LaTeX template prepared (`lni-author-template.tex` with authors and structure).
- [ ] Motivation written.
- [ ] Models included.
- [ ] SVM approach documented.
- [ ] Experiments documented.
- [ ] Simulation documented.
- [ ] Limitations discussed.
- [ ] References included.
- [ ] Paper reviewed by all members.
- [ ] Final document uploaded to Moodle (ZIP: PDF + all UPPAAL files).

## Submission
- Moodle submission: **July 10, 11:59 PM** (per final guideline; supersedes the earlier July 7 date).
- Format: LaTeX, CPS Seminar / LNI template.
- Length: max 10 pages.

# 9. Weekly Progress Log

## Checklist
- [x] Progress updated weekly.
- [x] Open problems documented.
- [x] Decisions documented.
- [x] Next steps defined.
- [x] GitHub updated after important changes.

| Date | Completed Work | Problems / Risks | Decisions | Next Steps |
|------|----------------|------------------|-----------|------------|
| 2026-05-15 | Lab exercises 01-07 finalized and presented; notebooks uploaded to Moodle per person | Classification-based steering too coarse for smooth control | Move to continuous steering targets (SVR regression) with geometric labeling | Gather real data in the Science Truck |
| 2026-05-18 | Science Truck data gathered (17,046 camera frames); feature pipeline built (trapezoid ROI, 3-band sampling) | Lighting noise and foliage blobs cause false line detections | Trapezoid ROI + morphological cleanup + row-span blob rejection | Train and tune SVR |
| 2026-05-19 | Tuned RBF SVR uploaded (grid search with TimeSeriesSplit; C=5, gamma=0.1, epsilon=0.01) | Adjacent-frame leakage would inflate scores | Temporal block split (last 20% held out); scaler fit on train only | Test on vehicle, collect critical scenarios |
| 2026-05-21 | Sharp-turn underfitting fixed (3× curve sample weights); final model `Trapezoid_V2_sharp_turns.pkl` committed to GitHub (Test MAE 0.0075, R² 0.9909) | Gains above throttle 0.40 untested | PD gain table per throttle band, conservative for high speeds | Competition |
| 2026-05-22 | Science Truck competition - **placed among the top teams** | - | - | Start truck platooning scenario work |
| 2026-06-04 | Milestone 1: 4 scenarios described (READMEs) and modelled in SysML/UML, committed to GitHub | Communication-failure write-up drifted off-topic (intersection controllers) | Keep the V2V truck-platooning framing for all documentation | Define communication protocols |
| 2026-06-11 | Milestone 2: data/signals/events and protocols specified per scenario; per-scenario UPPAAL timed automata created | Coordinating shared channel names across scenarios | Common channel set (statusUpdate, emergencyBrake, commFailure, …) | Control behaviour model |
| 2026-06-18 | Milestone 3: control behaviour specified (distance keeping, emergency braking, comm-failure fallback) | Emergency brake must be receivable from every state | Model emergencyBrake as a broadcast channel | Integrate everything |
| 2026-06-25 | Milestone 5: integrated UPPAAL model (LeadTruckControl, FollowerTruckControl, DistanceController, CommunicationMonitor) | Early versions had unreachable/deadlocking states | Restructure follower automaton; add safeDistance guard for safe mode | Verification |
| 2026-07-03 | Final verification: `A[] not deadlock` **passed** in UPPAAL; result stored in model file | - | Final model version frozen | Presentation + report |
| 2026-07-08 | Documentation phase: organization notebook completed; report material collected | Tight deadlines (slides July 9, report July 10) | Slides prepared in parallel by the team | Submit slides, write and submit final report + ZIP |

# 10. Final Self-Check Before Submission

## Technical checklist
- [x] Repository is complete.
- [x] Notebooks run from top to bottom (`01_extract_dataset` -> `02_train_svm`; `00_visualize_pipeline` for figures).
- [x] Data files or download instructions are available (`data/X_features.npy`, `y_labels.npy`, `steering.csv`).
- [x] Models are saved (`Trapezoid_V2_sharp_turns.pkl`; UPPAAL XMLs per scenario + integrated model).
- [x] Simulation can be executed or demonstrated (UPPAAL symbolic simulator + saved deadlock-freedom verification).
- [x] Figures and results are reproducible.

## Scientific checklist
- [x] Problem is clearly defined (truck platooning: line following + coordinated platoon control).
- [x] Dataset is documented (17,046 Science Truck frames, 6 features, geometric labels).
- [x] Methods are explained (feature pipeline, SVR tuning, timed automata, verification).
- [x] Results are evaluated (Test MAE 0.0075, R² 0.9909; `A[] not deadlock` passed; competition top placement).
- [ ] Limitations are discussed - to be written in the final report.
- [ ] References are included - to be added in the final report.

## Organisational checklist
- [x] Responsibilities are documented (Section 0 and 1 of this notebook).
- [x] Milestones are fulfilled (M1 June 4, M2 June 11, M3 June 18, M5 June 25).
- [ ] Moodle uploads are complete - slides due July 9, 1:00 PM; report ZIP due July 10, 11:59 PM.
- [x] GitHub repository is up to date.
- [ ] Final presentation is prepared - in progress (separately).
- [ ] Final paper is submitted - in progress.